name: deploy to cloudtype

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Connect
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
          scope: desktop-tutorial
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: freerecover/desktop-tutorial
          yaml: |-
            name: freerecover
            app: web
            options:
              nodeversion: "14"
              docbase: /dist
            context:
              git:
                ref: ${{ github.ref }}
                url: git@github.com:${{ github.repository }}.git
